/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RpcRouteImport } from './routes/rpc'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InternalVersionsRouteImport } from './routes/internal.versions'
import { Route as InternalAnalyticsRouteImport } from './routes/internal.analytics'
import { Route as ApiSplatRouteImport } from './routes/api.$'

const RpcRoute = RpcRouteImport.update({
  id: '/rpc',
  path: '/rpc',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalVersionsRoute = InternalVersionsRouteImport.update({
  id: '/internal/versions',
  path: '/internal/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalAnalyticsRoute = InternalAnalyticsRouteImport.update({
  id: '/internal/analytics',
  path: '/internal/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/rpc': typeof RpcRoute
  '/api/$': typeof ApiSplatRoute
  '/internal/analytics': typeof InternalAnalyticsRoute
  '/internal/versions': typeof InternalVersionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/rpc': typeof RpcRoute
  '/api/$': typeof ApiSplatRoute
  '/internal/analytics': typeof InternalAnalyticsRoute
  '/internal/versions': typeof InternalVersionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/health': typeof HealthRoute
  '/mcp': typeof McpRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/rpc': typeof RpcRoute
  '/api/$': typeof ApiSplatRoute
  '/internal/analytics': typeof InternalAnalyticsRoute
  '/internal/versions': typeof InternalVersionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/health'
    | '/mcp'
    | '/openapi.json'
    | '/rpc'
    | '/api/$'
    | '/internal/analytics'
    | '/internal/versions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/health'
    | '/mcp'
    | '/openapi.json'
    | '/rpc'
    | '/api/$'
    | '/internal/analytics'
    | '/internal/versions'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/health'
    | '/mcp'
    | '/openapi.json'
    | '/rpc'
    | '/api/$'
    | '/internal/analytics'
    | '/internal/versions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  HealthRoute: typeof HealthRoute
  McpRoute: typeof McpRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  RpcRoute: typeof RpcRoute
  ApiSplatRoute: typeof ApiSplatRoute
  InternalAnalyticsRoute: typeof InternalAnalyticsRoute
  InternalVersionsRoute: typeof InternalVersionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rpc': {
      id: '/rpc'
      path: '/rpc'
      fullPath: '/rpc'
      preLoaderRoute: typeof RpcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/versions': {
      id: '/internal/versions'
      path: '/internal/versions'
      fullPath: '/internal/versions'
      preLoaderRoute: typeof InternalVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/analytics': {
      id: '/internal/analytics'
      path: '/internal/analytics'
      fullPath: '/internal/analytics'
      preLoaderRoute: typeof InternalAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  HealthRoute: HealthRoute,
  McpRoute: McpRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  RpcRoute: RpcRoute,
  ApiSplatRoute: ApiSplatRoute,
  InternalAnalyticsRoute: InternalAnalyticsRoute,
  InternalVersionsRoute: InternalVersionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
